apiVersion: v1
kind: Pod
metadata:
  name: server-2
  labels:
    app: abhi
spec:
  containers:
  - image: herekar/abhi-server:14
    imagePullPolicy: IfNotPresent
    name: server
  restartPolicy: Always
