apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod2
  name: pod2
spec:
  nodeName: gke-marcus-containerd-default-pool-9168869a-9szw
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources:
      limits:
        cpu: 1000m
        memory: "100Mi"
      requests:
        cpu: 5m
