apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod4
  name: pod4
spec:
  nodeName: gke-abhijit-standard-1-default-pool-b736b064-xz89
  restartPolicy: Never
  containers:
  - image: ubuntu
    imagePullPolicy: Always
    name: ubuntu
    command:
      - /bin/bash
      - "-c"
      - |-
        echo hello world
        echo sleeping for 10
        sleep 10
        echo exiting with error now
        exit 66
    resources:
      limits:
        cpu: 1000m
        memory: "100Mi"
      requests:
        cpu: 5m
