apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod5
  name: pod5
spec:
  nodeName: gke-abhijit-standard-1-default-pool-b736b064-xz89
  containers:
  - image: ubuntu
    imagePullPolicy: Always
    name: ubuntu
    command:
      - /bin/bash
      - "-x"
      - "-c"
      - |-
        echo killing container here now
        #dd if=/dev/zero of=/dev/shm/fill bs=1MB count=1000
        yes | tr \\n x | head -c $((1024*1024*1024)) | grep n
        echo command finished
    resources:
      limits:
        cpu: 1000m
        memory: "100Mi"
      requests:
        cpu: 5m
